version = "2"

[tracker]
api_url = "http://tracker:1212"
private = false
url = "udp://tracker:6969"

[database]
connect_url = "sqlite:///var/lib/torrust/index/database/e2e_testing_sqlite3.db?mode=rwc"

[mail]
port = 1025
server = "mailcatcher"
