[metadata]
schema_version = "2.0.0"

[logging]
#threshold = "off"
#threshold = "error"
#threshold = "warn"
threshold = "info"
#threshold = "debug"
#threshold = "trace"

[core]
listed = false
private = false

[core.database]
path = "/var/lib/torrust/tracker/database/e2e_testing_sqlite3.db"

[http_api]
bind_address = "0.0.0.0:1212"
